/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihancruddesktop.ui.master;

/**
 *
 * @author KENDAY
 */

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import latihancruddesktop.Main;
import latihancruddesktop.domain.Peserta;
import latihancruddesktop.ui.tableModel.MasterPesertaTableModel;
import latihancruddesktop.utils.DatabaseConnection;
import latihancruddesktop.utils.ErrorDialog;
import latihancruddesktop.utils.TableUtil;

public class MasterPeserta extends javax.swing.JPanel {
    
    public static final String PANEL_NAME = "Master Peserta";
    private static MasterPeserta panel;
    private List<Peserta> listPeserta;
    private Peserta peserta;

    /**
     * Creates new form MasterPeserta
     */
    public MasterPeserta() {
        initComponents();
        loadDataToTable();
        tblPeserta.getSelectionModel().addListSelectionListener(new TableSelection());
    }
    
    public static MasterPeserta getPanel() {
        if (panel == null) {
            panel = new MasterPeserta();
        }
        
        return panel;
    }
    
    private class TableSelection implements ListSelectionListener {
       
@Override
public void valueChanged(ListSelectionEvent e) {
if (e.getValueIsAdjusting()) {
return;
}
if (tblPeserta.getSelectedRow() >= 0) {
peserta = listPeserta.get(tblPeserta.getSelectedRow());
}
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPeserta = new javax.swing.JTable();

        jToolBar1.setRollover(true);

        btnTambah.setText("Tambah");
        btnTambah.setFocusable(false);
        btnTambah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTambah.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTambah);

        btnEdit.setText("Edit");
        btnEdit.setFocusable(false);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEdit);

        btnHapus.setText("Hapus");
        btnHapus.setFocusable(false);
        btnHapus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHapus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHapus);

        btnTutup.setText("Tutup");
        btnTutup.setFocusable(false);
        btnTutup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTutup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTutup);

        tblPeserta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Alamat", "No Induk", "Jenis Kelamin"
            }
        ));
        jScrollPane1.setViewportView(tblPeserta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        
        try {
            if (tblPeserta.getSelectedRow() >= 0 && peserta != null) {
            peserta = new FormDialogPeserta().editAnggota(peserta);
            if (peserta != null) {
                
            Main.getPesertaDao().editPeserta(peserta,DatabaseConnection.getConnection());
            loadDataToTable();
            
            }
            } else {
            JOptionPane.showMessageDialog(Main.getMainForm(),
            "Tidak ada data yang ingin di edit !!",
            "Terjadi Kesalahan !!",
            JOptionPane.ERROR_MESSAGE);
            }
            } catch (Exception e) {
            ErrorDialog.showErrorDialog(e);
            }
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        
try {
    
peserta = new FormDialogPeserta().showDialog();

if (peserta != null) {
    
Main.getPesertaDao().insertPeserta(peserta,DatabaseConnection.getConnection());
loadDataToTable();

}
} catch (Exception e) {
    
ErrorDialog.showErrorDialog(e);
}
        
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        
        Main.getMainForm().getMainTabbedPane().remove(this);
        panel = null;

    }//GEN-LAST:event_btnTutupActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
      
        try {
        if (tblPeserta.getSelectedRow() >= 0 && peserta != null) {
        Main.getPesertaDao().hapusPeserta(peserta,DatabaseConnection.getConnection());  
        loadDataToTable();
        } else {
        JOptionPane.showMessageDialog(Main.getMainForm(),
        "Tidak ada data yang ingin di hapus !!",
        "Terjadi Kesalahan !!",
        JOptionPane.ERROR_MESSAGE);
        }
        } catch (Exception e) {
        ErrorDialog.showErrorDialog(e);
        }

    }//GEN-LAST:event_btnHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTutup;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tblPeserta;
    // End of variables declaration//GEN-END:variables

private void loadDataToTable() {
try {
listPeserta = Main.getPesertaDao().getAllPeserta(DatabaseConnection.getConnection());
if (!listPeserta.isEmpty()) {
tblPeserta.setModel(new MasterPesertaTableModel(listPeserta));
} else {
tblPeserta.setModel(new MasterPesertaTableModel(new ArrayList<Peserta>()));
TableUtil.initColumn(tblPeserta);
}
} catch (SQLException ex) {
ErrorDialog.showErrorDialog(ex);
}
}
}
