/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihancruddesktop.ui.master;

/**
 *
 * @author KENDAY
 */

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import latihancruddesktop.Main;
import latihancruddesktop.domain.Kelas;
import latihancruddesktop.ui.tableModel.MasterKelasTableModel;
import latihancruddesktop.utils.DatabaseConnection;
import latihancruddesktop.utils.ErrorDialog;
import latihancruddesktop.utils.TableUtil;

public class MasterKelas extends javax.swing.JPanel {
    
    public static final String PANEL_NAME = "Master Kelas";
    private static MasterKelas panel;
    private List<Kelas> listKelas;
    private Kelas kelas;
    /**
     * Creates new form MasterKelas
     */
    public MasterKelas() {
        initComponents();
        loadDataToTable();
        tblKelas.getSelectionModel().addListSelectionListener(new TableSelection());
    }
    
        
    public static MasterKelas getPanel() {
        if (panel == null) {
            panel = new MasterKelas();
        }
        
        return panel;
    }
    
 private class TableSelection implements ListSelectionListener {
       
@Override
public void valueChanged(ListSelectionEvent e) {
if (e.getValueIsAdjusting()) {
return;
}
if (tblKelas.getSelectedRow() >= 0) {
kelas = listKelas.get(tblKelas.getSelectedRow());
}
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKelas = new javax.swing.JTable();

        jToolBar1.setRollover(true);

        btnTambah.setText("Tambah");
        btnTambah.setFocusable(false);
        btnTambah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTambah.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTambah);

        btnEdit.setText("Edit");
        btnEdit.setFocusable(false);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEdit);

        btnHapus.setText("Hapus");
        btnHapus.setFocusable(false);
        btnHapus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHapus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHapus);

        btnTutup.setText("Tutup");
        btnTutup.setFocusable(false);
        btnTutup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTutup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTutup);

        tblKelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Kelas", "Nama Peserta"
            }
        ));
        jScrollPane1.setViewportView(tblKelas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed

     try {

        kelas = new FormDialogKelas().showDialog();

        if (kelas != null) {
    
        Main.getKelasDao().insertKelas(kelas,DatabaseConnection.getConnection());
        loadDataToTable();

        }
        } catch (Exception e) {
    
        ErrorDialog.showErrorDialog(e);
        }  

    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
            
            try {
            if (tblKelas.getSelectedRow() >= 0 && kelas != null) {
            kelas = new FormDialogKelas().editAnggota(kelas);
            if (kelas != null) {
                
            Main.getKelasDao().editKelas(kelas,DatabaseConnection.getConnection());
            loadDataToTable();
            
            }
            } else {
            JOptionPane.showMessageDialog(Main.getMainForm(),
            "Tidak ada data yang ingin di edit !!",
            "Terjadi Kesalahan !!",
            JOptionPane.ERROR_MESSAGE);
            }
            } catch (Exception e) {
            ErrorDialog.showErrorDialog(e);
            }
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed

        try {
        if (tblKelas.getSelectedRow() >= 0 && kelas != null) {
        Main.getKelasDao().hapusKelas(kelas,DatabaseConnection.getConnection());  
        loadDataToTable();
        } else {
        JOptionPane.showMessageDialog(Main.getMainForm(),
        "Tidak ada data yang ingin di hapus !!",
        "Terjadi Kesalahan !!",
        JOptionPane.ERROR_MESSAGE);
        }
        } catch (Exception e) {
        ErrorDialog.showErrorDialog(e);
        }
       
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed

        Main.getMainForm().getMainTabbedPane().remove(this);
        panel = null;
    }//GEN-LAST:event_btnTutupActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTutup;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tblKelas;
    // End of variables declaration//GEN-END:variables

private void loadDataToTable() {
try {
listKelas = Main.getKelasDao().getAllKelas(DatabaseConnection.getConnection());
if (!listKelas.isEmpty()) {
tblKelas.setModel(new MasterKelasTableModel(listKelas));
} else {
tblKelas.setModel(new MasterKelasTableModel(new ArrayList<Kelas>()));
TableUtil.initColumn(tblKelas);
}
} catch (SQLException ex) {
ErrorDialog.showErrorDialog(ex);
}
}

}
